export default {
  OPEN_DECISION_MODAL: "ModalConstant.OPEN_DECISION_MODAL",
  CLOSE_DECISION_MODAL: "ModalConstant.CLOSE_DECISION_MODAL",
  OPEN_VIDEO_MODAL: "ModalConstant.OPEN_VIDEO_MODAL",
  CLOSE_VIDEO_MODAL: "ModalConstant.CLOSE_VIDEO_MODAL",
  OPEN_BUSY_MODAL: "ModalConstant.OPEN_BUSY_MODAL",
  CLOSE_BUSY_MODAL: "ModalConstant.CLOSE_BUSY_MODAL"
}