export default {
  SIGNING_IN: "Session.SIGNING_IN",
  SIGNED_IN: "Session.SIGNED_IN",
  SIGNIN_FAILED: "Session.SIGNIN_FAILED",
  SIGN_OUT: "Session.SIGN_OUT",
  SIGNOUT_FAILED: "Session.SIGNOUT_FAILED",
  SIGNING_OUT: "Session.SIGNING_OUT",
  SIGNED_OUT: "Session.SIGNED_OUT",
}
