export default {
  SIGNIN_INPROGRESS: "Session.SIGNIN_INPROGRESS",
  SIGNED_IN: "Session.SIGNED_IN",
  SIGN_OUT: "Session.SIGN_OUT",
  SIGNIN_FAILED: "Session.SIGNIN_FAILED",
  SIGNOUT_INPROGRESS: "Session.SIGNOUT_INPROGRESS",
  SIGNED_OUT: "Session.SIGNED_OUT",
}
